version: "3.3"
services:
  service-1:
    image: luxterbot/service-1
    build: 
      context: .
      dockerfile: ./packages/service-1/Dockerfile
    ports:
      - "8081:8081"
    environment:
      DATABASE_STRING: mongodb://root:HLp3asdhHKJHDfu3hf98@host.docker.internal:27017/
  service-2:
    image: luxterbot/service-2
    build: 
      context: .
      dockerfile: ./packages/service-2/Dockerfile
    ports:
      - "8082:8082"
    environment:
      SECRET: 5ierh7Kay6MoKxx7QclbBq7I
  frontend:
    image: luxterbot/frontend
    build: 
      context: .
      dockerfile: ./packages/frontend/Dockerfile
    ports:
      - "8080:80"
    environment:
      SERVICE_1_URL: http://localhost:8081
  database:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: HLp3asdhHKJHDfu3hf98
      MONGO_INITDB_DATABASE: luxterbot
