version: "3.3"
services:
  service-1:
    image: luxterbot/service-1
    build: 
      context: .
      dockerfile: ./packages/service-1/Dockerfile
    expose:
      - "8081"
    environment:
      DATABASE_STRING: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@database:27017/
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=shared"
      - "traefik.http.routers.s1.rule=Host(`service-1.bot.luxterful.eu`)"
      - "traefik.http.services.s1.loadbalancer.server.port=8081"
      - "traefik.http.routers.s1.tls=true"
      - "traefik.http.routers.s1.tls.certresolver=acmeresolver"
    networks:
      - shared
      - internal

  service-2:
    image: luxterbot/service-2
    build: 
      context: .
      dockerfile: ./packages/service-2/Dockerfile
    expose:
      - "8082"
    environment:
      SECRET: ${SECRET} 
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=shared"
      - "traefik.http.routers.s2.rule=Host(`service-2.bot.luxterful.eu`)"
      - "traefik.http.services.s2.loadbalancer.server.port=8082"
      - "traefik.http.routers.s2.tls=true"
      - "traefik.http.routers.s2.tls.certresolver=acmeresolver"
    networks:
      - shared
      - internal
    
  frontend:
    image: luxterbot/frontend
    build: 
      context: .
      dockerfile: ./packages/frontend/Dockerfile
      args:
        - VUE_APP_SERVICE_1_URL=${VUE_APP_SERVICE_1_URL} 
    expose:
      - "8080"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=shared"
      - "traefik.http.routers.fe.rule=Host(`bot.luxterful.eu`)"
      - "traefik.http.services.fe.loadbalancer.server.port=8080"
      - "traefik.http.routers.fe.tls=true"
      - "traefik.http.routers.fe.tls.certresolver=acmeresolver"
    networks:
      - shared
      - internal
    
  database:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME} 
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - internal
    volumes:
      - ./database/init.js:/docker-entrypoint-initdb.d/init-mongo.js:ro

networks:
  shared:
    external: true
  internal:
    driver: bridge