log:
  level: debug

accessLog:
  filePath: /accesslogs/access.log
  format: json
  bufferingSize: 42
  fields:
    defaultMode: keep
    names:
      ClientAddr: drop
      ClientHost: drop
      ClientPort: drop
      ClientUsername: drop
    headers:
      defaultMode: keep
      names:
        X-Real-Ip: drop

providers:
  docker:
    watch: true
    exposedByDefault: false
    network: shared

api:
  insecure: true
  dashboard: false

entrypoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: :443

certificatesresolvers:
  acmeresolver:
    acme:
      email: lukas@luxterful.eu
      storage: /letsencrypt/acme.json
      httpchallenge:
        entrypoint: web
