# # # # # # # # # # # # # # # # #
#        IMPORTANT NOTE         #
# THIS FILE IS ONLY FOR TESTING #
# DONT DEPLOY IT TO PRODUCTION  #
# # # # # # # # # # # # # # # # #

version: "3.1"

services:
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8888:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: HLp3asdhHKJHDfu3hf98
      ME_CONFIG_MONGODB_URL: mongodb://root:HLp3asdhHKJHDfu3hf98@host.docker.internal:27017/
