# # # # # # # # # # # # # # # # # # #
#          IMPORTANT NOTE           #
# THIS FILE IS ONLY FOR DEVELOPMENT #
#   DONT DEPLOY IT TO PRODUCTION    #
# # # # # # # # # # # # # # # # # # #

version: "3.1"

services:
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8888:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@database:27017/
  
  database:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME} 
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - ./init.js:/docker-entrypoint-initdb.d/init-mongo.js:ro